services:
  db:
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      target: production
    command: npm start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

volumes:
  db_data:
